version: 2
jobs:
    test:
        working_directory: ~/app
        docker:
            - image: node
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Test
                command: npm run test
            - run:
                name: Lint
                command: npm run lint
    build-docker:
        working_directory: ~/app
        docker:
            - image: docker:latest
        steps:
            - checkout
            - run:
                name: Install Docker Compose
                command: ./.circleci/prepare-docker-compose.sh
            - setup_remote_docker
            - run:
                name: Build Docker Image
                command: docker-compose -f .circleci/docker-compose.yml build
            - deploy:
                name: Deploy docker image
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        ./.circleci/deploy-docker.sh
                    fi
    deploy-production:
        working_directory: ~/app
        docker:
            - image: buildpack-deps
        steps:
            - run:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/check-in-bot
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build-docker:
                filters:
                    branches:
                        only:
                            - master
                requires:
                    - test
            - deploy-production:
                filters:
                    branches:
                        only: master
                requires:
                    - build-docker
